name: React Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.4.0

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  publish:
    runs-on: ubuntu-latest
    needs: test
    env:
      IMAGE_NAME: react-spring-template-web
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT_CR }}


      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          # TODO: `1.0.0` should be actual version number
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:1.0.0
